name: challenge_for_skin_x
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  dio: 5.4.1
  easy_debounce: 2.0.3
  easy_localization: 3.0.5
  envied: 0.5.3
  envied_generator: 0.5.3
  flutter_secure_storage: 8.1.0
  flutter_svg: 2.0.10+1
  fluttertoast: 8.2.4
  go_router: 13.2.1
  json_annotation: 4.8.1
  oauth2_client: 3.2.2
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.8
  flutter_lints: 3.0.0
  json_serializable: 6.7.1

flutter:
  assets:
    - res/icons/
    - res/language/

  uses-material-design: true